// Generated by CoffeeScript 1.8.0
(function() {
  var fast_fib, fib, fib_index, memoize, print_elapsed_time, startTime;

  memoize = require("./memoize");

  fib_index = 40;

  console.log("Fibonacci index: " + fib_index + "\n");

  print_elapsed_time = function(startTime) {
    return console.log("Elapsed time: " + ((Date.now() - startTime) / 1000) + "s\n");
  };

  fib = function(n) {
    if (n < 2) {
      return n;
    }
    return fib(n - 1) + fib(n - 2);
  };

  startTime = Date.now();

  console.log("Calc slow fib function...");

  console.log(fib(fib_index));

  print_elapsed_time(startTime);

  fast_fib = memoize(function(n) {
    if (n < 2) {
      return n;
    }
    return fast_fib(n - 1) + fast_fib(n - 2);
  });

  startTime = Date.now();

  console.log("Calc with memoize wrapper...");

  console.log(fast_fib(fib_index));

  print_elapsed_time(startTime);

}).call(this);
