// Generated by CoffeeScript 1.8.0
(function() {
  var memoize,
    __slice = [].slice;

  memoize = function() {
    var arg;
    arg = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    this.cache = {};
    if (arg.length === 2) {
      this.fx = arg[arg.length - 1];
      this["yield"] = function(key) {
        if (this.cache[key] != null) {
          return this.cache[key];
        }
        return this.cache[key] = this.fx(key);
      };
      return this["yield"](arg[0]);
    } else {
      throw new Error("Usage: memoize initKeyArgValue, (keyArg) ->");
    }
  };

  module.exports = memoize;

}).call(this);
