// Generated by CoffeeScript 1.8.0
(function() {
  var memoize;

  memoize = function(fx) {
    var cache, memoized;
    cache = {};
    return memoized = function() {
      var i, key, keys, _i, _len;
      keys = [];
      for (_i = 0, _len = arguments.length; _i < _len; _i++) {
        i = arguments[_i];
        keys.push(i);
      }
      key = keys.join();
      if (cache[key] != null) {
        return cache[key];
      }
      return cache[key] = fx.apply(this, arguments);
    };
  };

  module.exports = memoize;

}).call(this);
